name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy only when pushing to main branch

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout Code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install Dependencies
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend

      # Step 4: Build React App
      - name: Build app
        run: npm run build
        working-directory: ./frontend

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./frontend/build
